import { type Product } from "./products";
import { type CategoryItem } from "./category-store";

export const demoCategories: CategoryItem[] = [
  {
    id: "hot-coffee",
    name: "قهوة مختصة وساخنة",
    description: "إسبريسو، فلات وايت، كورتادو، كيمكس، ومشروبات ساخنة مميزة",
    icon: "Coffee",
    createdAt: new Date("2026-01-01").toISOString(),
  },
  {
    id: "iced-coffee",
    name: "مشروبات مثلجة وكولد برو",
    description: "سبانش لاتيه مثلج، كولد برو، آيس كراميل، ومشروبات منعشة",
    icon: "IceCream",
    createdAt: new Date("2026-01-02").toISOString(),
  },
  {
    id: "pastries-sweets",
    name: "حلويات ومخبوزات طازجة",
    description: "تشيز كيك، كرواسون فرنسي، تيراميسو، ومولتن كيك فاخر",
    icon: "Cookie",
    createdAt: new Date("2026-01-03").toISOString(),
  },
  {
    id: "smoothies-shakes",
    name: "عصائر وسموذي طبيعي",
    description: "سموذي فواكه طبيعية، شيك الفراولة والبلوبيري، وماتشا لاتيه",
    icon: "Flame",
    createdAt: new Date("2026-01-04").toISOString(),
  },
  {
    id: "breakfast-toasts",
    name: "إفطار وتوستات كَيان",
    description: "توست الأفوكادو، كرواسون الرومي والجبن، وتشكيلة فطور متكاملة",
    icon: "Sparkles",
    createdAt: new Date("2026-01-05").toISOString(),
  },
  {
    id: "frappes-shakes",
    name: "فرابيه وميلك شيك",
    description: "فرابيه كراميل وشوكولاتة، أوريو شيك، وميلك شيك فستق ولوتس",
    icon: "IceCream",
    createdAt: new Date("2026-01-06").toISOString(),
  },
  {
    id: "mojitos-refreshers",
    name: "موهيتو ومشروبات منعشة",
    description: "موهيتو توت أزرق، باشن فروت فريش، وريد بول ميكس منعش",
    icon: "Flame",
    createdAt: new Date("2026-01-07").toISOString(),
  },
  {
    id: "artisanal-teas",
    name: "شاي وماتشا فاخرة",
    description: "ماتشا لاتيه ياباني، شاي إنجليزي، شاي أخضر بالياسمين وأعشاب",
    icon: "Coffee",
    createdAt: new Date("2026-01-08").toISOString(),
  },
  {
    id: "kayan-signatures",
    name: "سبيشال كَيان الحصري",
    description: "ابتكارات ومشروبات حصرية خاصة بكَيان كافيه بنكهات مبتكرة",
    icon: "Sparkles",
    createdAt: new Date("2026-01-09").toISOString(),
  },
  {
    id: "savory-sandwiches",
    name: "سندوتشات ومخبوزات مالحة",
    description: "سندوتش تونة مع أفوكادو، حلومي مشوي، وكرواسون جبنة مدخنة",
    icon: "Cookie",
    createdAt: new Date("2026-01-10").toISOString(),
  },
];

export const demoProducts: Product[] = [
  // 1. Hot Coffee
  {
    id: "demo-spanish-latte-hot",
    name: "سبانش لاتيه كَيان (Spanish Latte)",
    description: "إسبريسو غني ممزوج بالحليب الطازج المبخر والحليب المكثف المحلى مع رشة قرفة فاخرة.",
    price: 135,
    category: "قهوة مختصة وساخنة",
    images: [
      "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=800&q=80",
      "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80",
    ],
    featured: true,
    preparation_time: "4-6 دقائق",
    calories: 220,
    created_at: new Date("2026-01-10").toISOString(),
    updated_at: new Date("2026-01-10").toISOString(),
  },
  {
    id: "demo-flat-white",
    name: "فلات وايت (Flat White)",
    description: "دبل شوت إسبريسو مع طبقة حريرية متجانسة من المايكروفوم الغني بالنكهة.",
    price: 110,
    category: "قهوة مختصة وساخنة",
    images: [
      "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=800&q=80",
    ],
    featured: false,
    preparation_time: "3-5 دقائق",
    calories: 140,
    created_at: new Date("2026-01-11").toISOString(),
    updated_at: new Date("2026-01-11").toISOString(),
  },
  {
    id: "demo-cortado",
    name: "كورتادو كلاسيك (Cortado)",
    description: "توازن مثالي بنسبة 1:1 بين الإسبريسو المركز والحليب الدافئ المبخر بدقة.",
    price: 95,
    category: "قهوة مختصة وساخنة",
    images: [
      "https://images.unsplash.com/photo-1534778101976-62847782c213?w=800&q=80",
    ],
    featured: false,
    preparation_time: "3-4 دقائق",
    calories: 85,
    created_at: new Date("2026-01-12").toISOString(),
    updated_at: new Date("2026-01-12").toISOString(),
  },
  {
    id: "demo-v60-pourover",
    name: "قهوة مقطرة V60 إثيوبية",
    description: "تقطير يدوي لحبوب البن الإثيوبي الفاخر بإيحاءات الفواكه المجففة والزهور العطرية.",
    price: 130,
    category: "قهوة مختصة وساخنة",
    images: [
      "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80",
    ],
    featured: true,
    preparation_time: "5-7 دقائق",
    calories: 5,
    created_at: new Date("2026-01-13").toISOString(),
    updated_at: new Date("2026-01-13").toISOString(),
  },

  // 2. Iced Coffee
  {
    id: "demo-iced-spanish-latte",
    name: "آيس سبانش لاتيه (Iced Spanish)",
    description: "المشروب الأكثر طلباً: حليب مكثف مثلج مع طبقات الإسبريسو والحليب الطازج المنعش.",
    price: 145,
    category: "مشروبات مثلجة وكولد برو",
    images: [
      "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&q=80",
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80",
    ],
    featured: true,
    preparation_time: "3-5 دقائق",
    calories: 250,
    created_at: new Date("2026-01-14").toISOString(),
    updated_at: new Date("2026-01-14").toISOString(),
  },
  {
    id: "demo-cold-brew",
    name: "كولد برو منقوع 18 ساعة (Cold Brew)",
    description: "قهوة مقطرة ببطء على البارد لمدة 18 ساعة لمرارة منخفضة ونكهة نقية غنية بالشوكولاتة الداكنة.",
    price: 125,
    category: "مشروبات مثلجة وكولد برو",
    images: [
      "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800&q=80",
    ],
    featured: false,
    preparation_time: "2-3 دقائق",
    calories: 10,
    created_at: new Date("2026-01-15").toISOString(),
    updated_at: new Date("2026-01-15").toISOString(),
  },
  {
    id: "demo-iced-caramel-macchiato",
    name: "آيس كراميل ماكياتو (Iced Caramel)",
    description: "طبقات من الحليب البارد وشراب الفانيليا الطبيعي تعلوها صدمة إسبريسو وصوص الكراميل.",
    price: 140,
    category: "مشروبات مثلجة وكولد برو",
    images: [
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80",
    ],
    featured: false,
    preparation_time: "4-5 دقائق",
    calories: 280,
    created_at: new Date("2026-01-16").toISOString(),
    updated_at: new Date("2026-01-16").toISOString(),
  },

  // 3. Pastries & Sweets
  {
    id: "demo-san-sebastian",
    name: "سان سباستيان تشيز كيك مع الشوكولاتة",
    description: "تشيز كيك إسباني محمص ذائب القوام من الداخل، يُسكب عليه صوص الشوكولاتة البلجيكية الساخن.",
    price: 170,
    category: "حلويات ومخبوزات طازجة",
    images: [
      "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&q=80",
      "https://images.unsplash.com/photo-1508737027454-e6454ef45afd?w=800&q=80",
    ],
    featured: true,
    preparation_time: "3-5 دقائق",
    calories: 460,
    created_at: new Date("2026-01-17").toISOString(),
    updated_at: new Date("2026-01-17").toISOString(),
  },
  {
    id: "demo-french-croissant",
    name: "كرواسون فرنسي محشو بكريمة الفستق",
    description: "مخبوز يومياً بطبقات مقرمشة وهشة ومحشو بسخاء بكريمة الفستق الحلبي الطبيعي.",
    price: 130,
    category: "حلويات ومخبوزات طازجة",
    images: [
      "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&q=80",
    ],
    featured: false,
    preparation_time: "2-3 دقائق",
    calories: 380,
    created_at: new Date("2026-01-18").toISOString(),
    updated_at: new Date("2026-01-18").toISOString(),
  },
  {
    id: "demo-italian-tiramisu",
    name: "تيراميسو إيطالي أصلي (Tiramisu)",
    description: "بسكويت ليدي فينجر مغموس بإسبريسو كَيان مع كريمة الماسكاربوني وبودرة الكاكاو الفاخر.",
    price: 150,
    category: "حلويات ومخبوزات طازجة",
    images: [
      "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&q=80",
    ],
    featured: false,
    preparation_time: "2-4 دقائق",
    calories: 340,
    created_at: new Date("2026-01-19").toISOString(),
    updated_at: new Date("2026-01-19").toISOString(),
  },

  // 4. Smoothies & Fresh Juices
  {
    id: "demo-mango-passion-smoothie",
    name: "سموذي مانجو وباشن فروت استوائي",
    description: "قطع المانجو الاستوائية مع الباشن فروت المنعش وبذور الشيا الغنية بالفوائد.",
    price: 135,
    category: "عصائر وسموذي طبيعي",
    images: [
      "https://images.unsplash.com/photo-1546173159-315724a31d9b?w=800&q=80",
    ],
    featured: false,
    preparation_time: "4-5 دقائق",
    calories: 190,
    created_at: new Date("2026-01-20").toISOString(),
    updated_at: new Date("2026-01-20").toISOString(),
  },
  {
    id: "demo-mixed-berry-smoothie",
    name: "سموذي التوت المشكل (Berry Blast)",
    description: "توت أزرق، توت بري، فراولة طازجة مخفوقة مع الزبادي اليوناني والعسل الطبيعي.",
    price: 140,
    category: "عصائر وسموذي طبيعي",
    images: [
      "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&q=80",
    ],
    featured: false,
    preparation_time: "4-5 دقائق",
    calories: 210,
    created_at: new Date("2026-01-21").toISOString(),
    updated_at: new Date("2026-01-21").toISOString(),
  },

  // 5. Breakfast & Toasts
  {
    id: "demo-avocado-toast",
    name: "توست الأفوكادو بالجبن الفيتا والبيض",
    description: "خبز الساوردو المحمص مغطى بالأفوكادو المهروس، طماطم كرزية، وجبن الفيتا اليوناني وزيت الزيتون.",
    price: 160,
    category: "إفطار وتوستات كَيان",
    images: [
      "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80",
      "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&q=80",
    ],
    featured: true,
    preparation_time: "7-10 دقائق",
    calories: 390,
    created_at: new Date("2026-01-22").toISOString(),
    updated_at: new Date("2026-01-22").toISOString(),
  },
  {
    id: "demo-smoked-turkey-croissant",
    name: "كرواسون الديك الرومي المدخن والجبن",
    description: "كرواسون محمص ومحشو بشرائح الديك الرومي الفاخر والجبن السويسري الذائب مع الجرجير.",
    price: 155,
    category: "إفطار وتوستات كَيان",
    images: [
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
    ],
    featured: false,
    preparation_time: "5-7 دقائق",
    calories: 420,
    created_at: new Date("2026-01-23").toISOString(),
    updated_at: new Date("2026-01-23").toISOString(),
  },

  // 6. Frappes & Milkshakes
  {
    id: "demo-lotus-shake",
    name: "ميلك شيك بسكويت اللوتس المقرمش",
    description: "آيس كريم فانيليا مخفوق مع زبدة وبسكويت اللوتس الأصلي وكريمة الخفق الفاخرة.",
    price: 145,
    category: "فرابيه وميلك شيك",
    images: [
      "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&q=80",
    ],
    featured: false,
    preparation_time: "4-5 دقائق",
    calories: 450,
    created_at: new Date("2026-01-24").toISOString(),
    updated_at: new Date("2026-01-24").toISOString(),
  },

  // 7. Mojitos & Refreshers
  {
    id: "demo-blue-ocean-mojito",
    name: "موهيتو المحيط الأزرق (Blue Mojito)",
    description: "سيروب التوت الأزرق المنعش مع أوراق النعناع الفريش وقطع الليمون والمياه الغازية الفوارة.",
    price: 120,
    category: "موهيتو ومشروبات منعشة",
    images: [
      "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80",
    ],
    featured: false,
    preparation_time: "3-4 دقائق",
    calories: 130,
    created_at: new Date("2026-01-25").toISOString(),
    updated_at: new Date("2026-01-25").toISOString(),
  },

  // 8. Artisanal Teas & Matcha
  {
    id: "demo-matcha-latte",
    name: "آيس ماتشا لاتيه ياباني (Matcha Latte)",
    description: "بودرة ماتشا احتفالية درجة أولى مخفوقة بالحليب ودرجة خفيفة من شراب الفانيليا العضوي.",
    price: 160,
    category: "شاي وماتشا فاخرة",
    images: [
      "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=800&q=80",
    ],
    featured: true,
    preparation_time: "4-5 دقائق",
    calories: 160,
    created_at: new Date("2026-01-26").toISOString(),
    updated_at: new Date("2026-01-26").toISOString(),
  },

  // 9. Kayan Signatures
  {
    id: "demo-kayan-gold-signature",
    name: "كَيان جولد سيجنتشر (Kayan Signature)",
    description: "مزيج سري حصري يجمع بين كولد برو المركز ونكهة الفستق الكريمة ورقائق الذهب الصالحة للأكل.",
    price: 185,
    category: "سبيشال كَيان الحصري",
    images: [
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
    ],
    featured: true,
    preparation_time: "5-6 دقائق",
    calories: 290,
    created_at: new Date("2026-01-27").toISOString(),
    updated_at: new Date("2026-01-27").toISOString(),
  },

  // 10. Savory Sandwiches
  {
    id: "demo-grilled-halloumi-sandwich",
    name: "ساندوتش حلومي مشوي بالبيستو",
    description: "جبن الحلوم المشوي مع صوص الريحان والبيستو، طماطم مجففة، وجرجير في خبز الشيباتا الإيطالي.",
    price: 150,
    category: "سندوتشات ومخبوزات مالحة",
    images: [
      "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&q=80",
    ],
    featured: false,
    preparation_time: "6-8 دقائق",
    calories: 410,
    created_at: new Date("2026-01-28").toISOString(),
    updated_at: new Date("2026-01-28").toISOString(),
  },
];
